"""Owner-controlled local backups and verified restore.

A backup is two files in the owner-only ``backups/`` directory:

* ``<id>.sqlite3``: a consistent copy made with SQLite's online backup API
  (it includes committed WAL content), and
* ``<id>.json``: its manifest (format, app identity, schema version, size,
  sha256, creation time, label).

Both are written under temporary names, fsynced, verified (integrity check,
schema version, hash) and only then renamed into place, manifest last: a
backup without a manifest never counts. Ids are generated by Sam
(``sam-<UTC time>-<label>``); a restore accepts only such an id, resolved
inside the backups directory, so no user- or archive-supplied path is ever
opened or extracted. Backups never leave the machine and contain no
credentials (credentials are in the Keychain, never in the database).
Retention keeps the newest ``MAX_BACKUPS``.

Restore (the app must be stopped: the caller holds the instance lock):
validate the manifest, the hash, SQLite integrity and schema compatibility of
the backup FIRST; then make a safety backup of the current database; then
checkpoint and swap the file atomically. The live database is never touched
before the backup is fully validated.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import sqlite3
import uuid
from collections.abc import Callable
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from sam.storage.attempts import SQLiteAttemptStore
from sam.storage.database import Database, StorageError
from sam.storage.lock import InstanceLock
from sam.storage.migrations import CURRENT_VERSION, migrate
from sam.storage.paths import (
    APP_IDENTIFIER,
    BACKUP_DIR,
    LOCK_NAME,
    ensure_private_dir,
    ensure_private_file,
)

FORMAT = "sam.backup/1"
MAX_BACKUPS = 10
MAX_BACKUP_BYTES = 2 * 1024 * 1024 * 1024
BACKUP_ID = re.compile(r"^sam-\d{8}T\d{6}\d{6}Z-[a-z0-9-]{1,32}$")
_LABEL = re.compile(r"^[a-z0-9-]{1,32}$")


class BackupError(StorageError):
    pass


@dataclass(frozen=True)
class BackupInfo:
    backup_id: str
    created_at: str
    schema_version: int
    size: int
    sha256: str
    label: str


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def _fsync(path: Path) -> None:
    fd = os.open(path, os.O_RDONLY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def backup_dir(data_dir: Path) -> Path:
    return ensure_private_dir(data_dir / BACKUP_DIR)


def _check_copy(path: Path) -> int:
    """Open a copy read-only; return its schema version if it is intact."""

    try:
        conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    except sqlite3.Error:
        raise BackupError("backup_unreadable") from None
    try:
        rows = conn.execute("PRAGMA integrity_check").fetchall()
        if [r[0] for r in rows] != ["ok"]:
            raise BackupError("backup_integrity_failed")
        return int(conn.execute("PRAGMA user_version").fetchone()[0])
    except sqlite3.Error:
        raise BackupError("backup_integrity_failed") from None
    finally:
        conn.close()


def create_backup(
    db: Database, data_dir: Path, label: str = "manual", *, prune: bool = True
) -> BackupInfo:
    if not _LABEL.fullmatch(label):
        raise BackupError("backup_label_invalid")
    folder = backup_dir(data_dir)
    now = datetime.now(UTC)
    backup_id = f"sam-{now.strftime('%Y%m%dT%H%M%S%f')}Z-{label}"
    final = folder / f"{backup_id}.sqlite3"
    manifest = folder / f"{backup_id}.json"
    partial = folder / f".{backup_id}.sqlite3.partial"
    partial_manifest = folder / f".{backup_id}.json.partial"
    try:
        ensure_private_file(partial)
        dest = sqlite3.connect(str(partial))
        try:
            with db.lock:
                db.connection.backup(dest)
        finally:
            dest.close()
        _fsync(partial)
        schema = _check_copy(partial)
        size = partial.stat().st_size
        if size > MAX_BACKUP_BYTES:
            raise BackupError("backup_too_large")
        info = BackupInfo(
            backup_id, now.isoformat(), schema, size, _sha256(partial), label
        )
        ensure_private_file(partial_manifest)
        partial_manifest.write_text(
            json.dumps(
                {
                    "format": FORMAT,
                    "app": APP_IDENTIFIER,
                    "backup_id": info.backup_id,
                    "created_at": info.created_at,
                    "schema_version": info.schema_version,
                    "size": info.size,
                    "sha256": info.sha256,
                    "label": info.label,
                },
                sort_keys=True,
            )
        )
        _fsync(partial_manifest)
        os.replace(partial, final)
        os.replace(partial_manifest, manifest)  # manifest last: completion marker
        _fsync(folder)
    except BackupError:
        _discard(partial, partial_manifest)
        raise
    except (OSError, sqlite3.Error, StorageError):
        _discard(partial, partial_manifest)
        raise BackupError("backup_failed") from None
    if prune:
        prune_backups(data_dir)
    return info


def _discard(*paths: Path) -> None:
    for path in paths:
        try:
            path.unlink()
        except OSError:
            pass


def _read_manifest(folder: Path, backup_id: str) -> BackupInfo:
    if not BACKUP_ID.fullmatch(backup_id):
        raise BackupError("backup_id_invalid")
    manifest = folder / f"{backup_id}.json"
    if manifest.is_symlink() or not manifest.is_file():
        raise BackupError("backup_not_found")
    try:
        data = json.loads(manifest.read_text())
        info = BackupInfo(
            backup_id=str(data["backup_id"]),
            created_at=str(data["created_at"]),
            schema_version=int(data["schema_version"]),
            size=int(data["size"]),
            sha256=str(data["sha256"]),
            label=str(data["label"]),
        )
        valid = (
            data.get("format") == FORMAT
            and data.get("app") == APP_IDENTIFIER
            and info.backup_id == backup_id
            and re.fullmatch(r"[0-9a-f]{64}", info.sha256) is not None
        )
    except (OSError, ValueError, KeyError, TypeError):
        raise BackupError("backup_manifest_invalid") from None
    if not valid:
        raise BackupError("backup_manifest_invalid")
    return info


def list_backups(data_dir: Path) -> tuple[BackupInfo, ...]:
    folder = data_dir / BACKUP_DIR
    if not folder.is_dir() or folder.is_symlink():
        return ()
    found: list[BackupInfo] = []
    for manifest in folder.glob("sam-*.json"):
        try:
            found.append(_read_manifest(folder, manifest.stem))
        except BackupError:
            continue
    return tuple(sorted(found, key=lambda b: b.backup_id, reverse=True))


def prune_backups(data_dir: Path, keep: int = MAX_BACKUPS) -> int:
    folder = data_dir / BACKUP_DIR
    removed = 0
    for info in list_backups(data_dir)[keep:]:
        _discard(
            folder / f"{info.backup_id}.json", folder / f"{info.backup_id}.sqlite3"
        )
        removed += 1
    return removed


def verify_backup(data_dir: Path, backup_id: str) -> BackupInfo:
    """Every check a restore needs, touching nothing."""

    folder = data_dir / BACKUP_DIR
    info = _read_manifest(folder, backup_id)
    copy = folder / f"{backup_id}.sqlite3"
    if copy.is_symlink() or not copy.is_file():
        raise BackupError("backup_not_found")
    if copy.stat().st_size != info.size or _sha256(copy) != info.sha256:
        raise BackupError("backup_hash_mismatch")
    schema = _check_copy(copy)
    if schema != info.schema_version:
        raise BackupError("backup_manifest_invalid")
    if schema > CURRENT_VERSION or schema < 1:
        raise BackupError("backup_schema_incompatible")
    return info


def _copy(source: Path, target: Path) -> None:
    ensure_private_file(target)
    with source.open("rb") as src, target.open("wb") as dst:
        for block in iter(lambda: src.read(1 << 20), b""):
            dst.write(block)
    _fsync(target)


def validate_candidate(data_dir: Path, source: Path) -> None:
    """Full validation of a backup BEFORE it can become the live database.

    Runs on a throwaway copy (the backup itself is never modified): SQLite
    integrity, foreign keys, the schema migrated to this build, the
    external-action attempt invariants (every row parses; the durable
    uniqueness indexes accept the data), and every domain repository loading
    and validating its own records. Any failure refuses the restore."""

    scratch = data_dir / f".restore-check-{uuid.uuid4().hex}.sqlite3"
    try:
        _copy(source, scratch)
        db = Database(scratch)
        try:
            if db.integrity_problems():
                raise BackupError("backup_integrity_failed")
            if db.query("PRAGMA foreign_key_check"):
                raise BackupError("backup_foreign_keys_invalid")
            migrate(db)
            SQLiteAttemptStore(db).all()
            for load in _load_domains():
                load(db)
        except BackupError:
            raise
        except Exception:
            raise BackupError("backup_contents_invalid") from None
        finally:
            db.close()
    finally:
        _discard(*(Path(f"{scratch}{suffix}") for suffix in ("", "-wal", "-shm")))


def restore_backup(data_dir: Path, db_path: Path, backup_id: str) -> BackupInfo:
    """Replace the live database with a fully validated backup.

    Exclusive: it claims the SAME instance lock a running Sam (desktop
    runtime or backend) holds for its whole life, including during
    migration and every durable external-action reservation. If any of them
    is active, the restore is refused (``InstanceLocked``), not warned about.

    Order: validate the backup completely; make and verify a safety backup
    of the current database; then swap atomically. A failure at any point
    leaves the live database unchanged. Returns the safety backup (or the
    restored backup's info when there was no live database).

    The sha256 manifest protects against accidental corruption, NOT against
    a malicious local owner who can rewrite both the backup and its manifest:
    there is no cryptographic authenticity."""

    lock = InstanceLock(data_dir / LOCK_NAME)
    lock.claim()  # raises InstanceLocked while any Sam process is active
    try:
        return _restore_locked(data_dir, db_path, backup_id)
    finally:
        lock.release()


def _restore_locked(data_dir: Path, db_path: Path, backup_id: str) -> BackupInfo:
    info = verify_backup(data_dir, backup_id)
    folder = data_dir / BACKUP_DIR
    source = folder / f"{backup_id}.sqlite3"
    validate_candidate(data_dir, source)
    safety: BackupInfo | None = None
    if db_path.exists():
        try:
            live = Database(db_path)
        except StorageError:
            raise BackupError("current_database_unreadable") from None
        try:
            # no pruning here: it must never remove the backup being restored
            safety = create_backup(live, data_dir, label="pre-restore", prune=False)
            live.checkpoint()
        finally:
            live.close()
        verify_backup(data_dir, safety.backup_id)
    staging = db_path.with_name(db_path.name + ".restoring")
    try:
        _copy(source, staging)
        if _sha256(staging) != info.sha256:
            raise BackupError("backup_hash_mismatch")
        for suffix in ("-wal", "-shm"):
            _discard(Path(f"{db_path}{suffix}"))
        os.replace(staging, db_path)
        _fsync(db_path.parent)
    except BackupError:
        _discard(staging)
        raise
    except OSError:
        _discard(staging)
        raise BackupError("restore_failed") from None
    prune_backups(data_dir)
    return safety or info


def _load_domains() -> tuple[Callable[[Database], object], ...]:
    from sam.storage.career import SQLiteCareerRepository
    from sam.storage.knowledge import SQLiteKnowledgeStore
    from sam.storage.memory import SQLiteMemoryStore
    from sam.storage.proactive import SQLiteProactiveRepository
    from sam.storage.professional import SQLiteProfessionalRepository

    return (
        SQLiteMemoryStore,
        SQLiteKnowledgeStore,
        SQLiteProfessionalRepository,
        SQLiteCareerRepository,
        SQLiteProactiveRepository,
    )


__all__ = [
    "BACKUP_ID",
    "FORMAT",
    "MAX_BACKUPS",
    "BackupError",
    "BackupInfo",
    "create_backup",
    "list_backups",
    "prune_backups",
    "restore_backup",
    "validate_candidate",
    "verify_backup",
]
