/// Every command the webview may call is declared here. Only these become
/// ACL permissions (`allow-<command>`); nothing else is invokable.
const COMMANDS: &[&str] = &[
    "sam_status",
    "sam_chat",
    "sam_knowledge_list",
    "sam_knowledge_query",
    "sam_knowledge_ingest",
    "sam_knowledge_remove",
    "sam_memory_search",
    "sam_tools",
    "sam_permissions",
    "sam_revoke_grant",
    "sam_activity",
    "sam_decide_confirmation",
    "sam_voice_utterance",
    "sam_speak",
    "sam_identity_status",
    "sam_identity_enroll_begin",
    "sam_identity_enroll_sample",
    "sam_identity_enroll_complete",
    "sam_identity_enroll_cancel",
    "sam_identity_delete",
    "sam_guest_challenge",
    "sam_guest_start",
    "sam_guest_end",
    "sam_models_status",
    "sam_models_preferences",
    "sam_professional_profile",
    "sam_professional_ingest",
    "sam_professional_review",
    "sam_professional_remove",
    "sam_professional_query",
    "sam_proactive_overview",
    "sam_proactive_create",
    "sam_proactive_update",
    "sam_proactive_delete",
    "sam_proactive_run",
    "sam_proactive_notification",
    "sam_proactive_scheduler",
    "sam_career_overview",
    "sam_career_opportunity",
    "sam_career_fit",
    "sam_career_draft",
    "sam_career_submit",
    "sam_career_contact",
    "sam_career_outreach",
    "sam_career_send",
    "sam_career_preferences",
    "sam_voice_wake",
    "sam_voice_activation",
    "sam_voice_models_install",
    "sam_owner_setup",
    "sam_restart_backend",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
